development:
- cmd: ganache-cli
  cmd_settings:
    accounts: 10
    evm_version: istanbul
    gas_limit: 1200000000000000
    mnemonic: brownie
    port: 8545
  host: http://127.0.0.1
  id: development
  name: Ganache-CLI
- cmd: ethnode
  cmd_settings:
    port: 8545
  host: http://127.0.0.1
  id: geth-dev
  name: Geth Dev
- cmd: ganache-cli
  cmd_settings:
    accounts: 10
    evm_version: istanbul
    fork: mainnet
    gas_limit: 1200000000000000
    mnemonic: brownie
    port: 8545
    chain_id: 10
  host: http://127.0.0.1
  id: mainnet-fork
  name: Ganache-CLI (Mainnet Fork)
  timeout: 120
- cmd: ganache-cli
  cmd_settings:
    accounts: 10
    evm_version: istanbul
    fork: bsc-main
    gas_limit: 1200000000000000
    mnemonic: brownie
    port: 8545
  host: http://127.0.0.1
  id: bsc-main-fork
  name: Ganache-CLI (BSC-Mainnet Fork)
  timeout: 120
- cmd: ganache-cli
  cmd_settings:
    accounts: 10
    evm_version: istanbul
    fork: ftm-main
    gas_limit: 12000000
    mnemonic: brownie
    port: 8545
  host: http://127.0.0.1
  id: ftm-main-fork
  name: Ganache-CLI (FTM-Mainnet Fork)
  timeout: 120
- cmd: ganache-cli
  cmd_settings:
    unlock:
      - 0x42d2f9f84EeB86574aA4E9FCccfD74066d809600
      - 0xc28c6970D8A345988e8335b1C229dEA3c802e0a6
      - 0x4F987B24bD2194a574bB3F57b4e66B7f7eD36196
    accounts: 10
    evm_version: istanbul
    fork: arbitrum-one
    gas_limit: 1200000000000000
    mnemonic: brownie
    port: 8545
    chain_id: 421610
  timeout: 120
  host: http://127.0.0.1
  id: arbitrum-main-fork
  name: Ganache-CLI (Arbitrum-Mainnet Fork)
- cmd: ganache-cli
  cmd_settings:
    accounts: 10
    default_balance: 100000 ether
    evm_version: istanbul
    fork: avalanche-mainnet
    gas_limit: 20000000
    mnemonic: brownie
    port: 8545  
  host: http://127.0.0.1
  id: avalanche-main-fork
  name: Ganache-CLI (Avalanche-Mainnet Fork)
  timeout: 120
live:
- name: Ethereum
  networks:
  - chainid: 1
    explorer: https://api.etherscan.io/api
    host: https://mainnet.infura.io/v3/$WEB3_INFURA_PROJECT_ID
    id: mainnet
    name: Mainnet (Infura)
  - chainid: 3
    explorer: https://api-ropsten.etherscan.io/api
    host: https://ropsten.infura.io/v3/$WEB3_INFURA_PROJECT_ID
    id: ropsten
    name: Ropsten (Infura)
  - chainid: 4
    explorer: https://api-rinkeby.etherscan.io/api
    host: https://rinkeby.infura.io/v3/$WEB3_INFURA_PROJECT_ID
    id: rinkeby
    name: Rinkeby (Infura)
  - chainid: 5
    explorer: https://api-goerli.etherscan.io/api
    host: https://goerli.infura.io/v3/$WEB3_INFURA_PROJECT_ID
    id: goerli
    name: Goerli (Infura)
  - chainid: 42
    explorer: https://api-kovan.etherscan.io/api
    host: https://kovan.infura.io/v3/$WEB3_INFURA_PROJECT_ID
    id: kovan
    name: Kovan (Infura)
- name: Ethereum Classic
  networks:
  - chainid: 61
    explorer: https://blockscout.com/etc/mainnet/api
    host: https://www.ethercluster.com/etc
    id: etc
    name: Mainnet
  - chainid: 6
    explorer: https://blockscout.com/etc/kotti/api
    host: https://www.ethercluster.com/kotti
    id: kotti
    name: Kotti
- name: Binance Smart Chain
  networks:
  - chainid: 97
    explorer: https://api-testnet.bscscan.com/api
    host: https://data-seed-prebsc-1-s1.binance.org:8545
    id: bsc-test
    name: Testnet
  - chainid: 56
    explorer: https://api.bscscan.com/api
    host: https://bsc-dataseed.binance.org
    id: bsc-main
    name: Mainnet
- name: Fantom Opera
  networks:
  - chainid: 4002
    explorer: https://explorer.testnet.fantom.network
    host: https://rpc.testnet.fantom.network
    id: ftm-test
    name: Testnet
  - chainid: 250
    explorer: https://api.ftmscan.com/api
    host: https://rpcapi.fantom.network
    id: ftm-main
    name: Mainnet
- name: Avalanche
  networks:
  - chainid: 43114
    explorer: https://snowtrace.io/
    host: https://api.avax.network/ext/bc/C/rpc
    id: avalanche-mainnet
    name: mainnet
  - chainid: 43113
    explorer: https://testnet.snowtrace.io/
    host: https://api.avax-test.network/ext/bc/C/rpc
    id: fuji-testnet
    name: testnet
  - chainid: 43112
    host: https://api.avax.network/ext/bc/C/rpc
    id: avash
    name: local
- name: Arbitrum
  networks:
  - chainid: 42161
    explorer: https://arbiscan.io
    host: https://arb1.arbitrum.io/rpc
    id: arbitrum-one
    name: Mainnet
  - chainid: 421611
    explorer: https://rinkeby-explorer.arbitrum.io/#/
    host: https://rinkeby.arbitrum.io/rpc
    id: arbitrum-rinkeby
    name: Testnet
